### ISSUE TITLE
BlissOS isn't not booting properly on my laptop

### ISSUE THREAD

**Issue by mdjihadkabir** [BlissRoms-x86/support#10]
### Description

On BlissOS's latest version, my laptop doesn't boot when it has less than 100% charge, and even if it boots with 100% charge, if I reconnect the power, it gets shut down. But it's not happening on Windows 11. What should I do?

### Reproduction steps

```bash
Case 1:
1. Trying to boot with <100% battery
2. BlissOS animation loading
3. Just before completion, shuts down.

Case 2:
1. Booted successfully with 100% battery charge
2. Disconnecteded the power & reconnected it
3. BlissOS gets shut down.
```

### Category

Bootup

### OS Version

16.x

**Comment by hmtheboy154** [comment]
BlissOS 16 issue should be reported here : https://github.com/BlissOS/bug_reports/issues

Also you haven't told us the laptop you use Bliss on
