### ISSUE TITLE
🐛 [BUG] - <title>Can't click on buildings in the game （Rise of Kingdoms） （bliss OS16.9.7）

### ISSUE THREAD

**Issue by Pengbo15** [BlissRoms-x86/support#105]
### Description

Cannot click on buildings in the game （Rise of Kingdom）cannot move or upgrade buildings, Bliss OS version 16.9.7

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Category

Other

### OS Version

16.x

**Comment by UknowEtheG** [comment]
Thank you for reporting this issue 

Unfortunately you have not properly provided enough details to do anything with this bug report. 

You neglected to provide a log, a dmesg, screenshots or a video 

You also did not provide any details about your hardware you have installed to (such as the exact model names of your CPU and GPU) 


Without any of the above provided, the best solution we can provide you is to contact the game app developers and ask them to fully support x86 when they compile their app

**Comment by hmtheboy154** [comment]
BlissOS 16 reports are here : https://github.com/BlissOS/bug_reports

Also we have an option to turn mouse click as touch in Settings => Blissify => Misc
