### ISSUE TITLE
💡 [REQUEST] Adds hide mouse cursor option

### ISSUE THREAD

**Issue by uobikiemukot** [BlissRoms-x86/support#107]
### Summary

I'm using Blissos with qemu. There is a problem about the cursor when I stream or record Arknights. Android system cursor (Blissos) and GTK cursor (host XFCE desktop) appear at the same time.

![2024_1113_182008](https://github.com/user-attachments/assets/5743ef95-ccb8-40a2-a132-6aa747ee5c27)
![double_cursor_blissos](https://github.com/user-attachments/assets/cf8f69b8-4c02-4eee-8921-c63204ca99f8)

### Basic Example

Adds option to hide cursor in settings menu.

### Drawbacks

none

**Comment by Xtr126** [comment]
Can use `-display gtk,show-cursor=off` in QEMU command line 
https://wiki.archlinux.org/title/QEMU#No_visible_Cursor

**Comment by uobikiemukot** [comment]
Thank you for your replay.

> Can use `-display gtk,show-cursor=off` in QEMU command line https://wiki.archlinux.org/title/QEMU#No_visible_Cursor

I know this option. But I also would like to record Arknights without cursor. OBS could ignore XFCE desktop cursor but cannot ignore Android system cursor.
And I often use big mouse cursors while streaming. In that case, Android system cursor is annoying.
