### ISSUE TITLE
💡 [REQUEST] - New BlissOS version with an AOSP x64 system image found in ci.android.com

### ISSUE THREAD

**Issue by Gigglesheeetpi** [BlissRoms-x86/support#112]
### Start Date

12/04/2024

### Summary

New BlissOS release with Android 14 (Upside Down Cake)

Changes to do in the system image:
- Modify some files in the system.img for BlissOS appearance
- Modify the root filesystem to match Android x86 Project
- Add houdini for running ARM32/64 apps
- Some kind of root apps (su arleady installed in /system/xbin in the disk) 
- Add Termux or Term Oneplus
- Add Google Services and other GApps
- Modify the Settings app to include Bliss features

### Basic Example

No examples, just hypotheses

### Drawbacks

Pros:
- Bugfixes by Google
- 64-bit image (+ 32-bit ABI)
- Speed improved from the previous versions

Cons:
- Minium SDK Target is 21 (Android 5)
- System image half-tested by Google
- System image arleady de-googled

### Unresolved questions

Is it possible now with the system disk?

**Comment by Gigglesheeetpi** [comment]
sorry for my bad english (i'm italian)

**Comment by hmtheboy154** [comment]
ci.google ? You mean https://ci.android.com/ ?

**Comment by Gigglesheeetpi** [comment]
yes ive got wrong

**Comment by Gigglesheeetpi** [comment]
however, is this a good idea?
cuz i was finding androids x64 with android 14 but no one did it

**Comment by hmtheboy154** [comment]
> however, is this a good idea? 
No because these CI builds are not made for the same.

> cuz i was finding androids x64 with android 14 but no one did it
You wiill have it soon.

**Comment by utzcoz** [comment]
The ci.android.com only provides built from AOSP, and BlissOS is a downstream project of AOSP with so many other customized features/modifications from other projects and Bliss team, and BlissOS images are only provided by BlissOS team's infrastructure.

If you want to use some variants/versions of BlissOS, please join groups of BlissOS and check updates from BlissOS' websites or accounts(like twitter, XDA or other platforms supported by BlissOS team).

**Comment by Xtr126** [comment]
Not Android but for chromeOS there is a project that does this, modifying builds made by Google to boot on other PCs. We know it hasn't worked well in the long run, Google keeps making breaking changes.
