### ISSUE TITLE
🐛 [BUG] - Text mode installer: Unable to install grub

### ISSUE THREAD

**Issue by helamonster** [BlissRoms-x86/support#15]
### Description
Booting from `Bliss-v16.8-x86_64-UNOFFICIAL-k6.1-gapps-20230714.iso`

Using the text-mode installer, GRUB fails to install with this error:

`Installation failed! Either there’s no more free space or something is wrong with the installer`

Also, when I try to manually install GRUB from the shell, I get this odd response:

```
grub> root (hd0,1)
grub> setup (hd0)
 Checking if “/boot/grub/stage1” exists... no
 Checking if “/grub/stage1” exists... yes
 Checking if “/grub/stage2” exists... yes
 Checking if “/grub/ezfs_stage1_5” exist
 Running "embed /grub/e2fs_stage1_5 (hd0)"... 29 sectors are embedded.
succeeded
Segmentation fault
/ #

```
(grub then crashes and returns to the shell prompt)

I first tried using a VirtIO disk drive but GRUB was unable to see the disk (even though it was visible and I made the partitions). After that, I switched to a virtual SATA disk and GRUB was then able to see the device at least. But its still failing.

If I try to use GPT partition table, I get the following warning:
```
Found GPT on /dev/sda. The legacy GRUB can’t be installed
to GPT. Do you want to convert it to MBR?

WARNING: This is a dangerous operation. You should backup
your data first.

```
And if I choose 'yes' it seems to lock up and never returns.

Also, I originally had a GPT partition table on the disk, but the installer didn't seem to like that for some reason and said it doesn't support GPT.

Once I discovered the VBox/VMware boot option, the text-mode installer wasn't being used so wasn't a problem.

I would like to be able to use this installer to customize the partitions. Is the text-mode installer officially supported?

### Reproduction steps

```bash
1. Create a KVM VM (I used virt-manager and libvirtd) with a virtual SATA drive and CD-ROM
3. Put the BlissOS installer ISO in the virtual CD-ROM
4. Boot the VM
5. Choose the default boot option
6. Go through the setup process...
7. Create an msdos partition table with 2 partitions
8. Select the partition to install to
9. Use ext4 to format
a. Choose to install GRUB.
```

### Screenshots

All text mode

### Logs

None that I know of

### Category

Installer

### OS Version

Bliss-v16.8-x86_64-UNOFFICIAL-k6.1-gapps-20230714.iso

**Comment by electrikjesus** [comment]
This is a known issue we are in the process of resolving now. An update should be pushed in the coming weeks.

**Comment by hmtheboy154** [comment]
fixed
