### ISSUE TITLE
🐛 [BUG] - unable to install to qemu/kvm vm?

### ISSUE THREAD

**Issue by xpseudonym** [BlissRoms-x86/support#17]
### Description

1. I've dl ISOs from [here (v14)](https://sourceforge.net/projects/blissos-x86/files/Official/BlissOS14/OpenGApps/Generic/Bliss-v14.10-x86_64-OFFICIAL-opengapps-20230704.iso) and [here (v15)](https://sourceforge.net/projects/blissos-x86/files/Official/BlissOS15/Gapps/Generic/Bliss-v15.8.6-x86_64-OFFICIAL-gapps-20230703.iso).
2. I've followed instructions derived from Android-x86 and suggested [here](https://docs.blissos.org/installation/install-from-bootable-usb/#install-efi-from-bootable-usb) for both ISOs - the results are the same.
3. I am installing from the ISOs to QEMU/KVM via `virt-manager`.
4. My xml is [here](https://pastebin.com/kz5es7X7).
5. The install process seems to proceed successfully from selecting the install (last) option at the boot prompt, until I get to:
![image](https://github.com/BlissRoms-x86/support/assets/5032475/3809e218-227a-46be-a8fe-4bee1d25560b)
Where answering 'yes' proceeds straight to this screen:
![image](https://github.com/BlissRoms-x86/support/assets/5032475/d36ffe1c-8ae7-4e76-9d49-da2392aadec5)
Where I'm told the installer expects to write some 1768422 KB of stuff and so I am NOT asked:
![image](https://github.com/BlissRoms-x86/support/assets/5032475/0fc50172-b944-4964-9f21-949bcc0d4a25)
6. Instead, I jump on to to:
![image](https://github.com/BlissRoms-x86/support/assets/5032475/848590d3-d8d4-4e90-aac7-48f3d26b45ec)
And, very very frustratingly I DO NOT get time to 'Go grab another coffee!'  This causes me untold headaches due to unsatisfied caffeine addiction (but, that's not today's bug report...)
7. If I 'Run BlissOS-15.8.6' then it reboots in a count of 2 to the boot prompt menu at 4 above; If I 'Reboot' then it... (I don't need to repeat myself)
8. So, the install doesn't seem to be installing...
9. Also, if I choose the first item on the boot menu ('BlissOS... Live') then nothing appears to happen after dropping to the terminal and an invitation to 'Have A Truly Blissful Experience' (nice) except, I see the little cpu graph in `vert-manager` indicating repeated attempts to do something (boot?) before timing out:
![image](https://github.com/BlissRoms-x86/support/assets/5032475/326697b8-6273-4af5-8094-fa30df510e9e)
![image](https://github.com/BlissRoms-x86/support/assets/5032475/80253c05-1fcf-4464-acd5-ab78519e0cb4)
And, returning to the boot menu and repeat.

Any pointers to what needs to be done would be very helpful.  Thx

### Reproduction steps

```bash
See above.
```
### Category

Bootup

### OS Version

15.x

**Comment by levdopa** [comment]
![image](https://github.com/BlissRoms-x86/support/assets/94876600/3603e8d9-4c0d-43e7-981e-cda2847fd354)
same I just get this in my vm

**Comment by NuclearKitty** [comment]
same issue here on Proxmox 8.1.3 (QEMU) with both 14.10 and 15.8

![machine config](https://github.com/BlissRoms-x86/support/assets/117551422/1e7c4045-b9d4-4cea-860c-9a778d9af69f)

Trying to boot in debug mode hangs with some 1300 "urandom" messages. It proceeds to boot further after typing "exit" 2 times, but then gets stuck in a loop about missing directories.

![Debug](https://github.com/BlissRoms-x86/support/assets/117551422/7625dea5-df10-4457-bf12-721a2ce217a3)
![Debug 2](https://github.com/BlissRoms-x86/support/assets/117551422/93d390b3-91db-4af2-bdef-0fe35e5c816a)

**Comment by NuclearKitty** [comment]
@levdopa - I figured it out: It is about missing video acceleration. You can either boot from 

- "VM and other options" -> Debugging options -> Advanced options -> "Live CD VESA Mode - No GPU Acceleration"

![vesa](https://github.com/BlissRoms-x86/support/assets/117551422/4a216135-089c-4b82-9903-58ec2cd2df51)

---

or you can "apt install libgl1 libegl1" from your host shell and set "VirGL GPU" as your VM´s video device. Then you can boot

![machine config virgl](https://github.com/BlissRoms-x86/support/assets/117551422/66386fae-bd07-46e6-8e0f-ac49d9f1fefa)


- "VM and other options" -> QEMU/KVM - VirGL - SW FFMPEG

![virgl](https://github.com/BlissRoms-x86/support/assets/117551422/3b3edbd1-8c97-4ad3-948d-cee3979c0fcd)

---

Ive yet to figure out how to actually install it rather then just live boot it in QEMU, but at least it´s something for now...

**Comment by levdopa** [comment]
@NuclearKitty thanks!

**Comment by xpseudonym** [comment]
@NuclearKitty Many thanks - finally got round to the upgrade from Android-x86; feels like I'm at warp speed!

**Comment by darkworks** [comment]
what about internet working ? i see no wifi etc
