### ISSUE TITLE
🐛 [BUG] - Blinking framebuffer cursor and console text visible above desktop

### ISSUE THREAD

**Issue by helamonster** [BlissRoms-x86/support#18]
### Description

When running in "no hardware acceleration" mode from a qemu VM, even though BlissOS desktop is loaded, the framebuffer cursor is still visible as it blinks (at the left side of the screen).

In addition, whatever text you type with the console keyboard is echoed to the screen as well, but is usually quickly redrawn over. 

### Reproduction steps

```bash
1. Boot using the VMWare/VBox No HW acceleration option
2. Once BlissOS desktop shows, type some text with a keyboard connected to tty0 (virtual console)
```

### Screenshots

Screenshot: Console Text Visible in Graphical Environment:
https://imgur.com/a/tfOL6l9

### Category

Display

### OS Version

15.x

**Comment by electrikjesus** [comment]
Please look at the last item in this section of the command line options documentation: https://docs.blissos.org/configuration/configuration-through-command-line-parameters/#angle--software-rendering

**Comment by Xtr126** [comment]
QEMU with virglrenderer provides GPU acceleration and works on both Windows/Linux now. It should be used instead of software rendering when possible.

**Comment by hmtheboy154** [comment]
fixed, will available in future releases
