### ISSUE TITLE
🐛 [BUG] - Unable to launch install.ios file

### ISSUE THREAD

**Issue by CookieUndercover1212** [BlissRoms-x86/support#21]
### Description

I am unable to install Bliss OS. Every time I try to install it, it gives an error that says, "Virtual hard disk files can't be mounted from image files, or from removable media that isn't formatted with the NFTS file system." I don't know what that means or how to resolve it. I use Microsoft Surface Book 2 that runs on Windows 10. Let me know if there are any other spec info that you guys would need.

### Reproduction steps

```bash
1. Go to 'Downloads'
2. Double click on file, or right click on the file and click on 'Mount'
3. Double click on 'install.ios', or right click on the file and click on 'Mount'
4. Error window pops up: "Virtual hard disk files can't be mounted from image files, or from removable media that isn't formatted with the NFTS file system."
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
I'm sorry, I don't know how to do that.
```

### Logs

```bash
There is no log.
```

### Category

Other

### OS Version

14.x

**Comment by electrikjesus** [comment]
Most people that ignore the project documentation wouldn't have been able to figure out how to file a bug. Congratulations! 
But I suggest you seriously check out the install instructions on our docs https://docs.blissos.org/

Closing this ticket as we have no way to update user common sense
