### ISSUE TITLE
Wifi card not recognized

### ISSUE THREAD

**Issue by Florisv1** [BlissRoms-x86/support#28]
### Description

My Wifi card is not recognized:
I turn on Wifi, but none of the Wifi networks is recognized.  I can't select any Wifi network. 

My laptop is a [Lenovo Yoga 7 16IAH7 (82UF0054MH).
The BlissOs version I tried with are 14.10 and 15.8.6  (the versions I can download from Blissos.org), both have the same issue.

I tried all the different menu options, all the different ways to boot Blissos, but none of them worked with my Wifi card.

Output of the sudo lshw -C network command:
 description: Wireless interface
       product: Alder Lake-P PCH CNVi WiFi
       vendor: Intel Corporation
       physical id: 14.3
       bus info: pci@0000:00:14.3
       logical name: wlp0s20f3
       version: 01
       serial: f8:9e:94:68:26:d5
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress msix bus_master cap_list ethernet physical wireless
       configuration: broadcast=yes driver=iwlwifi driverversion=6.5.0-9-generic firmware=83.e8f84e98.0 so-a0-gf-a0-83.uc ip=192.168.1.138 latency=0 link=yes multicast=yes wireless=IEEE 802.11
       resources: iomemory:610-60f irq:16 memory:612d1cc000-612d1cffff

Other

### OS Version

16.x

**Comment by Florisv1** [comment]
Should I submit a pull request with the network driver modules? How should I submit these? Is there any instruction on how to do this?

**Comment by hmtheboy154** [comment]
test this build
https://github.com/BlissRoms-x86/manifest/issues/54#issuecomment-1849842383

**Comment by Florisv1** [comment]
> test this build [BlissRoms-x86/manifest#54 (comment)](https://github.com/BlissRoms-x86/manifest/issues/54#issuecomment-1849842383)

In your build the Wifi connection works: playing Youtube videos inside the webbrowser, opening web pages, etc.
 Only downloading apps using the Aurora store/downloading files using the webbrowser doesn't work in your build, there are some file saving issues in your build.  But that might be, because I was using a live CD to test everything ?

Also your build fixed my Bluetooth issues. I can find and play music on my Bluetooth speakers now.

In the Blissos versions supplied on the Blissos website Wifi only works when I use USB tethering and the Wifi connection of my phone. Bluetooth also didn't work using the Blissos builds from Blissos.org.

**Comment by Florisv1** [comment]
So this issue can be marked as closed/solved? Or not yet?

**Comment by hmtheboy154** [comment]
>  But that might be, because I was using a live CD to test everything ?

yes

> So this issue can be marked as closed/solved? Or not yet?

Closed, this is a testing build of 14.10 which uses latest stable kernel (6.6.6). Your hardware is too new for the kernel inside the builds at blissos.org
