### ISSUE TITLE
can't boot on efi because the iso parition table is in mbr

### ISSUE THREAD

**Issue by theotheroracle** [BlissRoms-x86/support#3]
the isos are all in mbr, and even though they have efi partitions, they can't be booted since they're in mbr . i did manage to boot the iso's with ventoy, but that didn't work for reasons i think are unrelated to the partition table

**Comment by guanzhangrtk** [comment]
Hi, can you please specify exactly which ISOs you are talking about? Exact URL will be helpful.

Better yet join the BlissLab Discord and ask your question there: https://discord.gg/wwc4Aua4fp

The latest test builds are only available at the URL which is posted at #release channel on the Discord.
