### ISSUE TITLE
🐛 [BUG] - 15.8.6, battery level "?"

### ISSUE THREAD

**Issue by promeneur** [BlissRoms-x86/support#30]
### Description

openSUSE Tumbleweed
QEMU 8.1
bliss 15.8.6
DOS partition 64 GB
RAM 8 GB

Script to launch bliss

`#!/bin/bash

qemu-kvm -enable-kvm
-m 8G -smp 4 -cpu host
-display gtk,gl=on,zoom-to-fit=off
-device virtio-vga-gl
-device qemu-xhci,p2=5,p3=5,id=xhci
-device usb-kbd
-device usb-mouse
-device usb-host,vendorid=0x046d,productid=0x0825
-device usb-host,vendorid=0x0b05,productid=0x190e
-device intel-hda
-device hda-duplex,audiodev=snd0
-audiodev pipewire,id=snd0
-boot menu=on
-nic bridge,mac=00:16:3e:4f:90:5a
~/QEMU_VM/Bliss-v15.8.6-x86_64-OFFICIAL-gapps-20230703.img
`
The battery level is "?"

I tried to set it to 100 % with the kernel command line in grub menu using "SET_FAKE_BATTERY_LEVEL=100" without any success

title BlissOS-15.8.6 2023-07-03 QEMO/KVM
kernel /android-2023-07-03/kernel quiet stack_depot_disable=on cgroup_disable=pressure root=/dev/ram0 noexec=off video=1680x1050x32 HWC=drm_minigbm GRALLOC=minigbm_arcvm FFMPEG_HWACCEL_DISABLE=1 SRC=/android-2023-07-03 SET_FAKE_BATTERY_LEVEL=100 

It's a problem because some apps as WhatsApp warns you they will stop because there is not enough battery, repeatedly then you can't use it.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Category

Other

### OS Version

15.x

**Comment by hmtheboy154** [comment]
this is not a bug, you device doesn't have a battery, of course it will said "?"

Check the Documentation on how to spoof the battery
https://docs.blissos.org/configuration/configuration-through-command-line-parameters/#battery-stats
