### ISSUE TITLE
🐛 [BUG] - Unable to utilize mouse in VirtualBox unless seamless mouse integration is disabled.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [BlissRoms-x86/support#34]
### Description

I expect that this is because, per https://github.com/BlissRoms-x86/support/issues/4#issuecomment-1420344171, the renderer is fairly new and consequently unevaluated.

### Reproduction steps

1.	Enable EFI.
1.	Boot.
1.	Invoke `com.android.settings`:
	1.	Cannot scroll.
	1.	Cannot move mouse.

### Screenshots

When https://github.com/BlissRoms-x86/support/issues/35#issue-2079200754 is fixed, I'll be able to provide a screenshot.

### Category
Display

### OS Version

15.x

**Comment by hmtheboy154** [comment]
![image](https://github.com/BlissRoms-x86/support/assets/39849246/f68b72c3-6098-4b1f-a668-90ee8635b7b6)
disable Mouse Interaction

**Comment by RokeJulianLockhart** [comment]
> https://github.com/BlissRoms-x86/support/issues/34#issuecomment-1889591603

@hmtheboy154, both of those icons?
