### ISSUE TITLE
🐛 [BUG] - Unable to boot in VirtualBox with HW acceleration enabled.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [BlissRoms-x86/support#35]
### Description

I was able to get it to boot once, but in that installation, it never booted again. I've not been able to get it to boot on subsequent installations.

### Screenshots

1.	**Ventoy**

	1.	Advanced options:
		> ![image](https://github.com/BlissRoms-x86/support/assets/42837531/5a93573b-2c5a-4fa4-a88f-35310d3a1387)
	1.	Automatic installation to selected storage device. This is replaced by the EFI entry when installed:
		> ![image](https://github.com/BlissRoms-x86/support/assets/42837531/15b0e5f9-a2a6-49da-97ca-d7987ab83769)

1.	**TUI installer**

	1.	> ![20240112T160840GMT](https://github.com/BlissRoms-x86/support/assets/42837531/9d8f86dc-a314-452f-a8e1-3f50df215741)
	1.	> ![image](https://github.com/BlissRoms-x86/support/assets/42837531/58482441-bb8e-49b4-aa76-55b106331c90)

1.	Boot:
	> ![image](https://github.com/BlissRoms-x86/support/assets/42837531/d457a449-8d85-40ba-a39e-e16a25a93af1)

### Category

Bootup

### OS Version

15.x

**Comment by RokeJulianLockhart** [comment]
Trying https://www.reddit.com/r/SurfaceLinux/comments/mgfkvy/comment/gzb75qh/?utm_source=share&utm_medium=web2x&context=3 didn't work:

> ![image](https://github.com/BlissRoms-x86/support/assets/42837531/f3321820-2235-4321-aedb-0fcc05980aef)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/BlissRoms-x86/support/issues/35#issue-2079200754

Found the solution! Boot using:

1.	> Advanced options
2.	> No Hardware Acceleration

**Comment by electrikjesus** [comment]
There has not been any updates to the virtual box modules or anything for VMware since Android 8 or 9, and kernel 4.4. So we do not use hardware acceleration for those kind of emulation solutions. This is well documented in our docs. 

If you require hardware acceleration, we suggest using QEMU/KVM

**Comment by electrikjesus** [comment]
It looks like we will have to update this document https://docs.blissos.org/installation/install-in-a-virtual-machine/install-in-virtualbox/

**Comment by RokeJulianLockhart** [comment]
> https://github.com/BlissRoms-x86/support/issues/35#issuecomment-1889676447

I've consequently tried to open an issue about https://github.com/BlissRoms-x86/Documentation/blob/main/Installation/install-in-a-virtual-machine/install-in-virtualbox.md, but https://github.com/BlissRoms-x86/Documentation/issues/new/choose#:~:text=Documentation%20issue,our%20documentation%20repository. takes me to https://github.com/BlissRoms-x86/docs/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc, which is an archived repository... There's no way to report documentation issues.
