### ISSUE TITLE
Acer Laptop / Intel 7260 Wireless not working due to RF_KILL

### ISSUE THREAD

**Issue by masscream** [BlissRoms-x86/support#4]
Hello, I've been struggling with this for a moment, maybe you may bring something new. I'm testing following  BlissOS distro, however I can't get wifi working. I verified the drivers (iwlwifi) are loaded in the kernel, the hardware buttons are toggled on (wifi is running fine in other dual-booted systems). The problem seems to be RF_KILL, which blocks the wireless device and there's no way to enable it. Toggling on/off the SW button has no effect, the device is just searching for new networks forever, without finding anything. RF_KILL command is not working, manual rewrite of /sys/class/rfkillX/state to 1 (phy0 has usually 2 which is confusing, thought of a boolean value...) is not working either, and its value is still 2, despite the root's attempt to rewrite the file.

On one forum I found an info, that probably disabling acer_wmi module could help, because the module is setting the RF_KILL block due to some bug, but this manual is for ubuntu and BlissOS does not have any /etc/modprobe.d/modprobe.conf...

I would be grateful for any advice, after so much time. Thank you.

Laptop: Acer Aspire 5750ZG
Wireless: Intel AC 7260
BlissOS build: BlissOS-14.3-x86_64-202107242243_k-android12-5.10.50-ax86_m-21.1.3_r-x86_foss_cros-hd

```
:/data/user/0/org.galexander.sshd/files # lsmod | grep iwlwifi
iwlwifi               262144  1 iwlmvm
cfg80211              860160  3 iwlmvm,mac80211,iwlwifi

127|:/sys/class/rfkill # dmesg | grep iwlwifi
[    8.406656] iwlwifi 0000:03:00.0: loaded firmware version 17.3216344376.0 7260-17.ucode op_mode iwlmvm
[    8.519160] iwlwifi 0000:03:00.0: Detected Intel(R) Dual Band Wireless AC 7260, REV=0x144
[    8.525313] iwlwifi 0000:03:00.0: reporting RF_KILL (radio disabled)
[    8.537465] iwlwifi 0000:03:00.0: base HW address: 11:22:33:44:55:66
[    9.630457] type=1400 audit(1675692252.084:23): avc: denied { module_load } for comm="ueventd" path="/system/lib/modules/5.10.50-android-x86_64-01113-g45e5663562e7/kernel/drivers/net/wireless/intel/iwlwifi/iwlwifi.ko" dev="loop0" ino=7820 scontext=u:r:ueventd:s0 tcontext=u:object_r:system_lib_file:s0 tclass=system permissive=1
[ 1392.735840] iwlwifi 0000:03:00.0: RF_KILL bit toggled to disable radio.

:/data/user/0/org.galexander.sshd/files # ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
3: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/tunnel6 :: brd ::
4: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether aa:bb:cc:dd:ee:ff brd ff:ff:ff:ff:ff:ff
5: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DORMANT group default qlen 1000
    link/ether 11:22:33:44:55:66 brd ff:ff:ff:ff:ff:ff

:/data/user/0/org.galexander.sshd/files # iw dev
phy#0
	Interface wlan0
		ifindex 5
		wdev 0x1
		addr 11:22:33:44:55:66
		type managed
		
:/data/user/0/org.galexander.sshd/files # ip link set wlan0 up
RTNETLINK answers: Operation not possible due to RF-kill

lrwxrwxrwx 1 root root 0 2023-02-06 15:04 rfkill2 -> ../../devices/pci0000:00/0000:00:1c.1/0000:03:00.0/ieee80211/phy0/rfkill2
lrwxrwxrwx 1 root root 0 2023-02-06 15:04 rfkill3 -> ../../devices/platform/acer-wmi/rfkill/rfkill3
lrwxrwxrwx 1 root root 0 2023-02-06 15:04 rfkill4 -> ../../devices/platform/acer-wmi/rfkill/rfkill4
lrwxrwxrwx 1 root root 0 2023-02-06 16:24 rfkill6 -> ../../devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.1/1-1.1:1.0/bluetooth/hci0/rfkill6
lrwxrwxrwx 1 root root 0 2023-02-06 16:24 rfkill7 -> ../../devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.6/1-1.6:1.0/bluetooth/hci1/rfkill7
:/sys/class/rfkill # cat rfkill*/name 
phy0
acer-wireless
acer-bluetooth
hci0
hci1
:/sys/class/rfkill # cat rfkill*/state                                                                                                                                                                            
2
1
1
1
1
:/sys/class/rfkill # rfkill
/system/bin/sh: rfkill: inaccessible or not found
```

**Comment by masscream** [comment]
Oh, I missed the new build. Testing in the Live CD mode and it looks like, the issue is present there as well with the same results and look...

**Comment by electrikjesus** [comment]
The fact that it needs read right in order to use RFkill X would likely require that it'd be installed and not running in live mode. Can you try that and let us know please?

**Comment by masscream** [comment]
Actually, when trying to install I got the error "Installation failed! Either there's no more free space or something is wrong with the installer !". I formatted the system partition the previous build was using clean, it has 10 GB of space. Tried ext4 and fat32 fs options, always the same and I'm not writing the grub. The error appears when it starts the file copy process however later from another OS, the partition space looks almost unused, although it has something already written from the installation... The new build struggles to run anyway, when booted in Live CD mode, it had kinda funny resolution. I could see only something running-moving, distorted, but nothing controllable. I succeeded only with the VESA mode 1024x768x32 so far. Anyway, this is it.

**Comment by hmtheboy154** [comment]
the Legacy grub is having a problem, also the `Make system R/W` option.

Also does your laptop has an Nvidia GPU inside ?

**Comment by hmtheboy154** [comment]
> The fact that it needs read/write in order to use RFkill X would likely require that it'd be installed and not running in live mode. Can you try that and let us know please?

or I can try to bring toybox's rfkill to Bliss, I brought `eject` before

**Comment by electrikjesus** [comment]
Bringing it to toybox might be the be better option

**Comment by hmtheboy154** [comment]
I think it's already there, try `toybox rfkill`

**Comment by masscream** [comment]
> the Legacy grub is having a problem, also the Make system R/W option.
I always make the R/W option. I reinstalled the old build and installation (same as Live CD) ran smoothly with no issues.

>Also does your laptop has an Nvidia GPU inside ?
Yes, it's one of these Optimus specials, which I never understood especially when it comes to non Windows systems... It has Intel GPU + nVidia used only in some specific cases.... I'm not quite sure which one the 14.3 was using but it ran smoothly with good resolution, I do not care which card it uses since it looks good, I'm not planning to use this distro for youtubing etc...

>I think it's already there, try toybox rfkill
Thank you, it's working.... however.... As I was toggling the buttons and let everything turned on, it probably become afraid and started working right after the installation of the old build. It's working now.

**Comment by hmtheboy154** [comment]
> I always make the R/W option. I reinstalled the old build and installation (same as Live CD) ran smoothly with no issues.

Skip that R/W option

> Yes, it's one of these Optimus specials, which I never understood especially when it comes to non Windows systems... It has Intel GPU + nVidia used only in some specific cases.... I'm not quite sure which one the 14.3 was using but it ran smoothly with good resolution, I do not care which card it uses since it looks good, I'm not planning to use this distro for youtubing etc...

set `nouveau.modeset=0` to disable the card and use only the Intel one, then you might get into the UI

**Comment by masscream** [comment]
> Skip that R/W option

And will I be able to modify the system then as root? That may come handy sometimes...


set nouveau.modeset=0 to disable the card and use only the Intel one, then you might get into the UI

> set `nouveau.modeset=0` to disable the card and use only the Intel one, then you might get into the UI

I'll give it a kick later..., I'm not rushing for the new build since the old will probably work the way I want. A pity that I can't run the BlissOS in VirtualBox so far. I would test if it even basically runs before I re-install the functional existing setup...

**Comment by masscream** [comment]
Actually the enjoyment was a little bit premature. It worked right after the installation, then after setting a few apps up, Magisk requested that "environmental change reboot" and since then it's not working again. The wifi is listed in rfkill as Hard blocked... so probably Magisk may have been causing this issue...

**Comment by Xtr126** [comment]
> And will I be able to modify the system then as root? That may come handy sometimes...  

You can just extract system.sfs with 7-zip instead.

> I'll give it a kick later..., I'm not rushing for the new build since the old will probably work the way I want. A pity that I can't run the BlissOS in VirtualBox so far. I would test if it even basically runs before I re-install the functional existing setup...

Old 14.3 builds don't have a working software renderer, so it wont work in VirtualBox/ VMWare.
In new 14.10 or 15.8.x builds they got swiftshader working again. 
Add `nomodeset` or `HWACCEL=0` to kernel cmdline in grub for VirtualBox. 
`ANGLE=1` if you want to try SwANGLE instead of swiftshader.

**Comment by masscream** [comment]
> You can just extract system.img from system.sfs with 7-zip instead (and delete .sfs).

Yeah but... for every, even minor change such a long way around? This is not an option for me although it's doable. Previous versions were working. Looks like I won't have any choice than to get the new build working anyway...

> Old 14.3 builds don't have a working software renderer, so it wont work in VirtualBox/ VMWare.
> In new 14.10 or 15.8.x builds they got swiftshader working again.
> Add `nomodeset` or `HWACCEL=0` to kernel cmdline in grub for VirtualBox.
> `ANGLE=1` if you want to try SwANGLE instead of swiftshader.

That worked, thanks, however the window was not accepting any input, from mouse, it did not even show its cursor....

**Comment by hmtheboy154** [comment]
turn mouse integration off
