### ISSUE TITLE
Lenovo Thinkpad 10 20e4 BlissOS 15.8.6 Foss No Sound Realtek ALC5672

### ISSUE THREAD

**Issue by NooB9496** [BlissRoms-x86/support#5]
Hello, I have a problem with no sound in the system. No application plays sound. Sometimes the system has stutters, freezes. I'm also not sure if gpu decoding works. I tested default boot and (Intel) w/ FFMPEG. 
[logcat_08-11-2023_18-17-14.txt](https://github.com/BlissRoms-x86/support/files/12323528/logcat_08-11-2023_18-17-14.txt)

**Comment by NooB9496** [comment]
New logcat after changing hal.audio.out 
[logcat_08-11-2023_19-10-02.txt](https://github.com/BlissRoms-x86/support/files/12323741/logcat_08-11-2023_19-10-02.txt)

**Comment by electrikjesus** [comment]
The logs just keep showing the control interface dying... Can you also please get the results of lsmod so we can see what is being detected?

**Comment by NooB9496** [comment]
Sorry, now I use windows 11 pro.
