### ISSUE TITLE
🐛 [BUG] - Install

### ISSUE THREAD

**Issue by dayvydrn** [BlissRoms-x86/support#51]
### Description

Lenovo 1 15amn7

Automatic installation presents error: DEFAULT BOOT DEVICE MISSING OR BOOT FAILED, notebook does not have legacy mode in setup.

Installation via Androidx86-Installer-for-Windows gives the error below:

error: no such device /AndroidOS/android.boot
error: file /AndroidOS/kernel not found
error: you need to load the kernel first

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Category

Bootup, Other

### OS Version

16.x

**Comment by electrikjesus** [comment]
Can you please add more contextual details to your issue? : 
- your hardware (CPU/GPU/RAM/etc)
- what build you are installing (build filename)
- what install method you are using
- also provide logs if possible

Thank you for helping us help you

**Comment by dayvydrn** [comment]
Not support processor AMD APU! Screen Black!

**Comment by electrikjesus** [comment]
If you're not going to follow our requests for more information and just reply with something barely related, we are not able to help you. 

Closing this thread. Please don't open a new one until you learn how to properly provide the info requested.
