### ISSUE TITLE
🐛 [BUG] - Play Services in FOSS version of Bliss OS?

### ISSUE THREAD

**Issue by junglized** [BlissRoms-x86/support#52]
### Description

Hi all.

I was wondering why there are play services installed in FOSS version of Bliss OS?

Additionally it can't be removed from Aurora store (where I found it on the first place).

![Screenshot_20240323-070126_Aurora Store](https://github.com/BlissRoms-x86/support/assets/26525585/736f4e54-62db-4d0f-9657-607c4717e578)

### Reproduction steps

```bash
1. Go to 'Aurora Store'
2. Click on 'Updates'
3. See update for PlayServices
```

### Category

Other

### OS Version

15.x

**Comment by electrikjesus** [comment]
This is not play services, it's microG

**Comment by junglized** [comment]
Oh I see. I'm surprised, because I have Calyx OS on my Pixel 3A and Google Play is not mentioned anywhere in the system, and it also works with MIcroG.

Is it the differce in implementation inside operating system or just different version of MicroG?
Which feauture of MicroG makes it to appear in Aurora store?

Thanks!

**Comment by electrikjesus** [comment]
If I remember correctly, they don't install fake store and I think the one you are using does. So that would be the only difference

**Comment by junglized** [comment]
Awesome. Thanks for your explanation! That concludes this topic.
