### ISSUE TITLE
🐛 [SOLVED] - Wireless debugging on ethernet

### ISSUE THREAD

**Issue by zaidranger** [BlissRoms-x86/support#65]
### Description

Since virtwifi is no longer used how do we mock the ethernet as wifi? i need this for a couple of apps too. Mainly because i wanted to screen share bliss os with other devices.

### Reproduction steps

```bash
1. Go to 'Android settings'
2. Click on 'Developer options'
3. Scroll down to 'Enable wireless debugging'
4. See error
```

### OS Version

14.10

**Comment by electrikjesus** [comment]
What version of Bliss are you using?

**Comment by zaidranger** [comment]
> What version of Bliss are you using? 
> 

14.10 and zenith

**Comment by Xtr126** [comment]
Add VIRT_WIFI=1 to kernel command line in grub https://docs.blissos.org/configuration/configuration-through-command-line-parameters/

**Comment by zaidranger** [comment]
> Add VIRT_WIFI=1 to kernel command line in grub https://docs.blissos.org/configuration/configuration-through-command-line-parameters/

Works on refind, thanks.
