### ISSUE TITLE
🐛 [BUG] - Microphone not working

### ISSUE THREAD

**Issue by wawawawa1212** [BlissRoms-x86/support#67]
### Description

Everything works, sound, touch, trackpad, etc. Only thing that bugs me is the fact that no app recognizes my microphone. Im running bliss os Zenith on a huawei laptop with a built in mic. The version im using is 16.9.6

### Category

Bug

### OS Version

Bliss os 16.9.6

**Comment by wawawawa1212** [comment]
Is anybody gonna help?

**Comment by wawawawa1212** [comment]
still waiting

**Comment by electrikjesus** [comment]
Closing this due to entitled user interactions.
