### ISSUE TITLE
🐛 Stable Download is not bootable

### ISSUE THREAD

**Issue by jhudsoncedaron** [BlissRoms-x86/support#72]
### Description

Download zip file is missing the boot .efi file.

### Reproduction steps

```bash
Zip file contains:

META-INF
apex_info.pb
payload.bin
payload_properties

Where's the .efi file? Without a .efi file and without a 2048 byte .bin file nothing's going to boot.

The instructions are trying to use Rufus to write this to a physical USB stick but I need a .ISO file to feed directly to QEMU.
```

### Category

Bootup

### OS Version

16.x

**Comment by electrikjesus** [comment]
You downloaded to the OTA zip, not the iso that you install from. 

Please utilize the documentation we provide for install methods that we support. Thank you

**Comment by jhudsoncedaron** [comment]
@electrikjesus You have the OTA file set to auto download from the sourceforge page.

**Comment by electrikjesus** [comment]
I think that's just the sourceforge default of downloading the latest upload

**Comment by jhudsoncedaron** [comment]
If you need a non default download on a page with an auto default, the documentation had better mention that. This page for example has no mention. https://docs.blissos.org/installation/install-in-a-virtual-machine/install-in-qemu/

**Comment by electrikjesus** [comment]
Updates https://github.com/BlissRoms-x86/Documentation/commit/f0b87d4fa72598cdd9a5e2de7022b04ba63c79b3

**Comment by jhudsoncedaron** [comment]
@electrikjesus  That's a good update. I had done Ctrl-F for iso and only got the one hit in the qemu launcher and was left puzzled how to convert the zip to a bootable iso; not realizing there was an iso to download.

**Comment by electrikjesus** [comment]
All good. We are currently in the process of migrating our docs to a better platform, and there are many updates on the way. So if you spot any other areas that we could help clear up any confusion before it happens, please let us know. 

Thanks!
