### ISSUE TITLE
Random reboots bliss zenith

### ISSUE THREAD

**Issue by andraluca44zp** [BlissRoms-x86/support#90]
### Description

Hi so i played around with this os using a mini pc with n100 and a touchscreen monitor and i had some issue but theres one big problem that makes unusable .
So after random time usually under 1h the bliss os logo appears like its reboot but its faster like coming up from sleep except the logo shows like its starting again and it kills all the apps with it.
So i cant make work more than 1h without os rebooting somehow what could be the issue.
I installed the os on internal nvme  efi 2gb 480gb left for os 
cpu n100
16gb ddr4
using a uperfect touchscreen monitor connected to it .
Bliss os zenith 16.9.6 generic gapps and foss used both have same issue random reboots.

I tried using older versions of bliss os but the wifi drivers dont work.

### Reproduction steps

```bash
1. blue zenith 16.9.6 generic installed from flash drive
2. after install it works but it reboots itself after random period of time

Cant test older versins of bliss os since drivers are not supported for n100.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Category

Bootup

### OS Version

16.x

**Comment by andraluca44zp** [comment]
it does this with other computer i tested with a n5095 same issue this os its a nightmare i tried 20 different veriosn 80% didnt have enough driver support for the somehow new cpu , on some older version there was no encoder for movies , kernelsu was outdated u couldnt install apps, even on latest zenith version theres issue with wifi , os crashing random times , and with other pc i tested even bluetooth detection has issues .

I just want the os to stop crashing at random times and killing the app its not usable and theres no other versions i can test since theres no driver support.

**Comment by andraluca44zp** [comment]
it is happening to other people too ? i tested with a n 5095 and the problem its still there i can only use zenith since the drivers are not support for older versions i can make wifi work but bluetooth has issue if i make the drivers work the cpu encoder doesnt work to watch movies so im stuck with zenith but the issue its that it reboots/restart the os not the pc every 1h or random times making it kinda unusable for online gaming

**Comment by hmtheboy154** [comment]
this is not the correct place, move to https://github.com/BlissOS/bug_reports
