### ISSUE TITLE
look like bliss is not taking care of developmental errors they persist along the releases 

### ISSUE THREAD

**Issue by Sai-On-Git** [BlissRoms-x86/support#91]
### Description

please provide support for issues #89 And #90 .This os is awsome and super smooth ,i need this os but i am not using this because issues #89 and #90 (mainly #89)

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by UknowEtheG** [comment]
You haven't provided any details about your device 

You haven't specified which exact ISO file name of the build you are installing and testing 

No logs provided 
No dmesg

Your "issue" reads as:
"I like your OS but you are not ironing out compatibility issues between hardware fast enough for my liking.  So let me point out two other issues that were submitted properly with information to help the development team, but I will not do the same.  Just submit so everybody is aware I'm waiting on more progress"



Thank you for your contribution

**Comment by hmtheboy154** [comment]
One more post like this then I'll ban you, either give more information to debug for your issue like Kernel log (dmesg) or no helping

**Comment by Sai-On-Git** [comment]
> One more post like this then I'll ban you, either give more information to debug for your issue like Kernel log (dmesg) or no helping

#89 is issue raised by me as i used and tested this os on my acer aspire es1 520 with amd e1 2500 radeon 8240 hd graphics and comming to problem my network card is Qualcom atheros ar956x with integrated bluetooth 4.0

**Comment by Sai-On-Git** [comment]
i provided all details in #89 but i dont think that we can collect logs because when os boots there is no problem when i use for sometime it disconnects in middle and i  see no error excet  'cant connect to this network',how to collect log for this . i seen same issue by multiple users and myself in all versions of 15,16 and zenith

**Comment by Sai-On-Git** [comment]
> You haven't provided any details about your device
> 
> You haven't specified which exact ISO file name of the build you are installing and testing
> 
> No logs provided No dmesg
> 
> Your "issue" reads as: "I like your OS but you are not ironing out compatibility issues between hardware fast enough for my liking. So let me point out two other issues that were submitted properly with information to help the development team, but I will not do the same. Just submit so everybody is aware I'm waiting on more progress"
> 
> Thank you for your contribution

i did provide detailed explanatiton of my problem and my device and network card specs in #89 (raised by me) with repetation steps have a look at it,i submitted as much as i can i dont have much technical knoledge

**Comment by Sai-On-Git** [comment]
> You haven't provided any details about your device
> 
> You haven't specified which exact ISO file name of the build you are installing and testing
> 
> No logs provided No dmesg
> 
> Your "issue" reads as: "I like your OS but you are not ironing out compatibility issues between hardware fast enough for my liking. So let me point out two other issues that were submitted properly with information to help the development team, but I will not do the same. Just submit so everybody is aware I'm waiting on more progress"
> 
> Thank you for your contribution

i used all versions iso of 15 ,16 and also zenith i have seen exactly same problem on my laptop,but contrarly i didnt see this issue in 14,

**Comment by Sai-On-Git** [comment]
> You haven't provided any details about your device
> 
> You haven't specified which exact ISO file name of the build you are installing and testing
> 
> No logs provided No dmesg
> 
> Your "issue" reads as: "I like your OS but you are not ironing out compatibility issues between hardware fast enough for my liking. So let me point out two other issues that were submitted properly with information to help the development team, but I will not do the same. Just submit so everybody is aware I'm waiting on more progress"
> 
> Thank you for your contribution
can u provide any testiting buld which has kernel supporting my network hardware Qualcomm atheros ar956x (ar9565/Qca9565) with integrated blutooth 4.0 . i can see that my current linux it ath9k driver and in my past linux i saw ath10k somewhere 
[Device Info20240921_081928.txt](https://github.com/user-attachments/files/17082559/Device.Info20240921_081928.txt)

provide some informatton how can i install drivers on my own

**Comment by gitmanbloggus** [comment]
> > You haven't provided any details about your device
> > You haven't specified which exact ISO file name of the build you are installing and testing
> > No logs provided No dmesg
> > Your "issue" reads as: "I like your OS but you are not ironing out compatibility issues between hardware fast enough for my liking. So let me point out two other issues that were submitted properly with information to help the development team, but I will not do the same. Just submit so everybody is aware I'm waiting on more progress"
> > Thank you for your contribution
> > can u provide any testiting buld which has kernel supporting my network hardware Qualcomm atheros ar956x (ar9565/Qca9565) with integrated blutooth 4.0 . i can see that my current linux it ath9k driver and in my past linux i saw ath10k somewhere
> > [Device Info20240921_081928.txt](https://github.com/user-attachments/files/17082559/Device.Info20240921_081928.txt)
> 
> provide some informatton how can i install drivers on my own

you cant

**Comment by gitmanbloggus** [comment]
it's baked into the kernel, which would take forever for you to figure out

**Comment by Sai-On-Git** [comment]
> it's baked into the kernel, which would take forever for you to figure out

https://github.com/android-generic/kernel-zenith/tree/6.9/drivers/net/wireless/ath
see this there are drivers for my network adapter in this zenith kernel  and there may be in 16.x because the kernel is same but i am facing problem with my network adapter how can i solve this

**Comment by gitmanbloggus** [comment]
> > it's baked into the kernel, which would take forever for you to figure out
> 
> https://github.com/android-generic/kernel-zenith/tree/6.9/drivers/net/wireless/ath
> see this there are drivers for my network adapter in this zenith kernel  and there may be in 16.x because the kernel is same but i am facing problem with my network adapter how can i solve this
> 

you would need to learn how to add drivers to the linux kernel, compile it, then compile bliss which is hard due to the hardware needed (I think)

**Comment by Xtr126** [comment]
> > > it's baked into the kernel, which would take forever for you to figure out
> > 
> > 
> > https://github.com/android-generic/kernel-zenith/tree/6.9/drivers/net/wireless/ath
> > see this there are drivers for my network adapter in this zenith kernel  and there may be in 16.x because the kernel is same but i am facing problem with my network adapter how can i solve this
> 
> you would need to learn how to add drivers to the linux kernel, compile it, then compile bliss which is hard due to the hardware needed (I think)

Kernel can be compiled independent from the Android system

**Comment by Sai-On-Git** [comment]
i think we don't need to compile or build any thing to add the drivers because there are drivers for my network adapter { i explored kernel drivers page } . i think they are not implemented or brought in to work by os in short i think this is a glitch and can besolved with little effort

**Comment by Sai-On-Git** [comment]
i need some technical support to solve this issue i have seen the same issue in 15.x ,16.x and also zenith build (all version gapps iso) . would it be anything better if i use foss ISOs , is there any major difference between two
