### ISSUE TITLE
🐛 [BUG] - "Display Over Other Apps" not working

### ISSUE THREAD

**Issue by RC128tech** [BlissRoms-x86/support#92]
### Description

Hello,

On my installation of Bliss Go 16.9.7 the function "Display Over Other Apps" does not work at all. When I want to start the Task bar, I'm getting the message this function is disabled because it slows down my phone. I can activate the function in the debug options, but it still doesn't work, even aber reboot.

This affects only the 16.9.7 image with gapps from September 11. An older 16.9.7 image without gapps didn't had this problem, the taskbar was working after granting permission.

Hardware: Dell XPS 9560 4K touchscreen (multitouch is working)
Install Medium: 16 GB USB 2.0 flash drive, MBR, EXT4
Install Images created with "WinSetupFromUSB 1.10 64bit" 

Question: How is the version scheme of BlissOS ? Is there a version 17 to expect soon?

Best Regards

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by Sai-On-Git** [comment]
if you are there using go build there is a setting named overcome limitations on low ram devices and developer option which are  needed to be enabled to let to you use this  feature on go builds

**Comment by RC128tech** [comment]
And where?

**Comment by Sai-On-Git** [comment]
i dont know where they are exactly because  i am not currently using it i think it would be somewhere in blissify or any other special settings i dont really remember but it is possible to use this feature on go builds

**Comment by hmtheboy154** [comment]
![image](https://github.com/user-attachments/assets/168d24e5-7bf5-4c87-ab8d-044b03556975)
 Blissify => Miscellaneous
