### ISSUE TITLE
🐛 [BUG] - <title> 屏幕息屏后无法再次唤醒。After pressing the power button, the screen cannot be awakened again

### ISSUE THREAD

**Issue by Fatira-Bucharles** [BlissRoms-x86/support#95]
### Description

按下电源键息屏后无法再次亮起屏幕，但多次按下或重新接入键盘后，键盘指示灯比如大小写指示灯会亮起，但不会熄灭。After pressing the power button, the screen cannot be awakened again, But the keyboard lights can be turned on, such as the uppercase and lowercase indicator lights.

### Reproduction steps

```bash
1. Go to 'the power button'
2. Click on 'Press the power button to turn off the screen'
3. Scroll down to 'press power button again when the screen is off'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
Device: HUAWEI MateBook E 2022
CPU：Intel® Core™ i7-1160G7
GPU: Intel® Iris® Xe Graphics (without discrete graphics)
RAM: 16G DDR4 3200MHz (Unknown manufacturer)
NIC: Intel® AX201 WiFi 6 160MHz (Unknown size, and unable to connect to the network)
Disk: 512G NVMe M.2 2280 SSD (Unknown manufacturer)
Screen: 12.6inch 16:10 2560*1600 touchscreen
SIM: Not supported
Boot mode: UEFI Only, no legacy BIOS boot

Bliss OS Version: 16.9.7-x86_64-OFFCIAL-gapps-20240911
If need any more information, please reply. I am very grateful for your efforts.
```

### Category

Display, Other

### OS Version

16.x

**Comment by gitmanbloggus** [comment]
> ### Description
> 按下电源键息屏后无法再次亮起屏幕，但多次按下或重新接入键盘后，键盘指示灯比如大小写指示灯会亮起，但不会熄灭。After pressing the power button, the screen cannot be awakened again, But the keyboard lights can be turned on, such as the uppercase and lowercase indicator lights.
> 
> ### Reproduction steps
> ```shell
> 1. Go to 'the power button'
> 2. Click on 'Press the power button to turn off the screen'
> 3. Scroll down to 'press power button again when the screen is off'
> 4. See error
> ```
> 
> ### Screenshots
> ```shell
> ![DESCRIPTION](LINK.png)
> ```
> 
> ### Logs
> ```shell
> Device: HUAWEI MateBook E 2022
> CPU：Intel® Core™ i7-1160G7
> GPU: Intel® Iris® Xe Graphics (without discrete graphics)
> RAM: 16G DDR4 3200MHz (Unknown manufacturer)
> NIC: Intel® AX201 WiFi 6 160MHz (Unknown size, and unable to connect to the network)
> Disk: 512G NVMe M.2 2280 SSD (Unknown manufacturer)
> Screen: 12.6inch 16:10 2560*1600 touchscreen
> SIM: Not supported
> Boot mode: UEFI Only, no legacy BIOS boot
> 
> Bliss OS Version: 16.9.7-x86_64-OFFCIAL-gapps-20240911
> If need any more information, please reply. I am very grateful for your efforts.
> ```
> 
> ### Category
> Display, Other
> 
> ### OS Version
> 16.x

seems to be a problem with idling
you can change it in kernel parameters (grub only I think)

**Comment by Fatira-Bucharles** [comment]
> > ### Description
> > 按下电源键息屏后无法再次亮起屏幕，但多次按下或重新接入键盘后，键盘指示灯比如大小写指示灯会亮起，但不会熄灭。After pressing the power button, the screen cannot be awakened again, But the keyboard lights can be turned on, such as the uppercase and lowercase indicator lights.
> > ### Reproduction steps
> > ```shell
> > 1. Go to 'the power button'
> > 2. Click on 'Press the power button to turn off the screen'
> > 3. Scroll down to 'press power button again when the screen is off'
> > 4. See error
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Screenshots
> > ```shell
> > ![DESCRIPTION](LINK.png)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Logs
> > ```shell
> > Device: HUAWEI MateBook E 2022
> > CPU：Intel® Core™ i7-1160G7
> > GPU: Intel® Iris® Xe Graphics (without discrete graphics)
> > RAM: 16G DDR4 3200MHz (Unknown manufacturer)
> > NIC: Intel® AX201 WiFi 6 160MHz (Unknown size, and unable to connect to the network)
> > Disk: 512G NVMe M.2 2280 SSD (Unknown manufacturer)
> > Screen: 12.6inch 16:10 2560*1600 touchscreen
> > SIM: Not supported
> > Boot mode: UEFI Only, no legacy BIOS boot
> > 
> > Bliss OS Version: 16.9.7-x86_64-OFFCIAL-gapps-20240911
> > If need any more information, please reply. I am very grateful for your efforts.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Category
> > Display, Other
> > ### OS Version
> > 16.x
> 
> seems to be a problem with idling you can change it in kernel parameters (grub only I think)

Although it is embarrassing to say it, but my english and programming skills are only have Junior high school level... I don't know how to programing so I don't know how to make it work by myself. By the way, I installed Bliss OS and then installed Win11 without using Bliss OS. Could this be related?

**Comment by gitmanbloggus** [comment]
> > > ### Description
> > > 按下电源键息屏后无法再次亮起屏幕，但多次按下或重新接入键盘后，键盘指示灯比如大小写指示灯会亮起，但不会熄灭。After pressing the power button, the screen cannot be awakened again, But the keyboard lights can be turned on, such as the uppercase and lowercase indicator lights.
> > > ### Reproduction steps
> > > ```shell
> > > 1. Go to 'the power button'
> > > 2. Click on 'Press the power button to turn off the screen'
> > > 3. Scroll down to 'press power button again when the screen is off'
> > > 4. See error
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### Screenshots
> > > ```shell
> > > ![DESCRIPTION](LINK.png)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### Logs
> > > ```shell
> > > Device: HUAWEI MateBook E 2022
> > > CPU：Intel® Core™ i7-1160G7
> > > GPU: Intel® Iris® Xe Graphics (without discrete graphics)
> > > RAM: 16G DDR4 3200MHz (Unknown manufacturer)
> > > NIC: Intel® AX201 WiFi 6 160MHz (Unknown size, and unable to connect to the network)
> > > Disk: 512G NVMe M.2 2280 SSD (Unknown manufacturer)
> > > Screen: 12.6inch 16:10 2560*1600 touchscreen
> > > SIM: Not supported
> > > Boot mode: UEFI Only, no legacy BIOS boot
> > > 
> > > Bliss OS Version: 16.9.7-x86_64-OFFCIAL-gapps-20240911
> > > If need any more information, please reply. I am very grateful for your efforts.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### Category
> > > Display, Other
> > > ### OS Version
> > > 16.x
> > 
> > seems to be a problem with idling you can change it in kernel parameters (grub only I think)
> 
> Although it is embarrassing to say it, but my english and programming skills are only have Junior high school level... I don't know how to programing so I don't know how to make it work by myself. By the way, I installed Bliss OS and then installed Win11 without using Bliss OS. Could this be related?

nah, just something about how your pc handles going into sleep mode
easily fixable
